version: '2.4'
services:
    report_backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports: [5000:3000]
        environment:
            - PORT=3000
            - HOST=localhost:3000
            - NODE_ENV=development
            - DEBUG=pw:api
        volumes:
            - ./src:/usr/src/app/src
        restart: always
